---
title: "wrangling using plant phenology data"
author: "An Bui"
date: "4/9/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(here)
library(lubridate)
```

```{r}
site_phenometrics_data <- read_csv(here::here("data","site_phenometrics_data.csv"))
```

```{r clean up site phenometrics data for use}
#### getting date from day of year ####
site_phenometrics_data$origin <- as.Date(paste0(site_phenometrics_data$Mean_First_Yes_Year, "-01-01"), tz = "UTC") - days(1)

site_phenometrics_data$newdate <- as.Date(dates$Mean_First_Yes_DOY, origin = site_phenometrics_data$origin, tz = "UTC")

#### add year and month columns ####
final_df <- site_phenometrics_data %>% 
  mutate(year = year(newdate),
         month = month(newdate)) %>% 
  select((1:16), year, month, (40:55))

#### write csv ####
write_csv(final_df, "phenometrics_data.csv")
```

```{r filter California observations only}
ca_pheno <- site_phenometrics_data %>%
  filter(State == "CA")
```

```{r select columns that you want}
select_columns <- ca_pheno %>% 
  select(1:4, Genus, Species, Common_Name, Phenophase_Description, Mean_First_Yes_Year, Mean_First_Yes_DOY)
```

```{r take out all rows with placeholders in year and DOY}
convert_NA <- select_columns %>% 
  filter(Mean_First_Yes_Year != -9999 &
           Mean_First_Yes_DOY != -9999)
```

```{r getting date from day of year}
# might be something to to at the beginning, because date wrangling is not really in the scope of this whole thing
convert_NA$origin <- as.Date(paste0(convert_NA$Mean_First_Yes_Year, "-01-01", tz = "UTC"))
convert_NA$newdate <- as.Date(dates$Mean_First_Yes_DOY, origin = convert_NA$origin, tz = "UTC")
```

```{r getting date info from newdate column and getting rid of other date columns}
new_dates <- convert_NA %>%
  mutate(year = year(newdate),
         month = month(newdate)) %>%
  select(-(9:12))
```

```{r make a plot of Joshua tree phenology}
#### wrangle the data ####
# make a new df where the genus and species columns are together
merge_sp <- new_dates %>% 
  unite("Genus_Species", Genus, Species)

# set levels for flowering descriptions
levels(merge_sp$Phenophase_Description) <- c("Flowers or flower buds", "Open flowers", "Pollen release (flowers)")

# filter data frame to only include Joshua trees
jt <- merge_sp %>% 
  filter(Genus_Species == "Yucca_brevifolia")

# summarize the number of times each observation occurs
jt_summary <- jt %>% 
  group_by(month, Phenophase_Description) %>% 
  tally()

#### plot in ggplot ####
ggplot(jt_summary, aes(x = month, 
                       y = n, 
                       fill = Phenophase_Description)) +
  geom_col(position = "dodge")
```

```{r make a plot of creosote bush}
# filter data for creosote bush
cb <- merge_sp %>% 
  filter(Common_Name == "creosote bush")

# summarize the number of times each observation occurs
cb_summary <- cb %>% 
  group_by(month, Phenophase_Description) %>% 
  tally()

#### plot in ggplot ####
ggplot(cb_summary, aes(x = month,
                       y = n,
                       fill = Phenophase_Description)) +
  geom_col(position = "dodge")
```

```{r plot creosote bush and joshua tree phenology together}
#### combine the two dataframes ####
# add a new column to each data frame so that you know which is which
cb_summary_name <- cb_summary %>% 
  mutate(species = "creosote bush")

jt_summary_name <- jt_summary %>% 
  mutate(species = "joshua tree")

# combine the dataframes
combined <- bind_rows(cb_summary_name, jt_summary_name) %>% 
  group_by(species, Phenophase_Description)

# # filter by open flowers
# open_flowers <- combined %>% 
#   filter(Phenophase_Description == "Open flowers")

ggplot(combined, aes(x = month,
                     y = n,
                     color = species,
                     shape = Phenophase_Description)) +
  geom_point() +
  geom_line()
```

